version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ilovepdf_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ilovepdf

  redis:
    image: redis:7.2-alpine
    container_name: ilovepdf_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongo_data:
  redis_data:
